<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GV2C5M4" failures="5" tests="11" name="Smoke" time="9.391" errors="0" timestamp="2021-07-21T11:35:27 EDT">
  <testcase classname="api_tests.PetStoreTest" name="addNewPet" time="3.596">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at api_tests.PetStoreTest.addNewPet(PetStoreTest.java:141)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- addNewPet -->
  <testcase classname="api_tests.PetStoreTest" name="addNewPetWithChainValidation" time="1.907"/>
  <testcase classname="api_tests.PetStoreTest" name="addNewPetWithInvalidJsonData" time="0.538">
    <failure type="java.lang.AssertionError" message="1 expectation failed.
Expected status code &amp;lt;500&amp;gt; but was &amp;lt;200&amp;gt;.
">
      <![CDATA[java.lang.AssertionError: 1 expectation failed.
Expected status code <500> but was <200>.

at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:674)
at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:126)
at io.restassured.specification.ResponseSpecification$statusCode$0.callCurrent(Unknown Source)
at io.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:134)
at io.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:89)
at io.restassured.internal.ValidatableResponseImpl.super$2$statusCode(ValidatableResponseImpl.groovy)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy:142)
at io.restassured.internal.ValidatableResponseImpl.statusCode(ValidatableResponseImpl.groovy)
at api_tests.PetStoreTest.addNewPetWithInvalidJsonData(PetStoreTest.java:212)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 43 stack frames]]>
    </failure>
  </testcase> <!-- addNewPetWithInvalidJsonData -->
  <testcase classname="api_tests.PetStoreTest" name="addNewPetWithJsonFile" time="0.485">
    <failure type="java.lang.AssertionError" message="expected [{
    &amp;quot;id&amp;quot;: 356098,
    &amp;quot;category&amp;quot;: {
        &amp;quot;id&amp;quot;: 2,
        &amp;quot;name&amp;quot;: &amp;quot;kitten&amp;quot;
    },
    &amp;quot;name&amp;quot;: &amp;quot;roar&amp;quot;,
    &amp;quot;photoUrls&amp;quot;: [
        &amp;quot;www.amazon.com&amp;quot;
    ],
    &amp;quot;tags&amp;quot;: [
        {
            &amp;quot;id&amp;quot;: 12,
            &amp;quot;name&amp;quot;: &amp;quot;roar&amp;quot;
        }
    ],
    &amp;quot;status&amp;quot;: &amp;quot;available&amp;quot;
}] but found [{
    &amp;quot;id&amp;quot;: 356098,
    &amp;quot;category&amp;quot;: {
        &amp;quot;id&amp;quot;: 2,
        &amp;quot;name&amp;quot;: &amp;quot;kitten&amp;quot;
    },
    &amp;quot;name&amp;quot;: &amp;quot;roar&amp;quot;,
    &amp;quot;photoUrls&amp;quot;: [
        &amp;quot;www.amazon.com&amp;quot;
    ],
    &amp;quot;tags&amp;quot;: [
        {
            &amp;quot;id&amp;quot;: 12,
            &amp;quot;name&amp;quot;: &amp;quot;roar&amp;quot;
        }
    ],
    &amp;quot;status&amp;quot;: &amp;quot;available&amp;quot;
}]">
      <![CDATA[java.lang.AssertionError: expected [{
    "id": 356098,
    "category": {
        "id": 2,
        "name": "kitten"
    },
    "name": "roar",
    "photoUrls": [
        "www.amazon.com"
    ],
    "tags": [
        {
            "id": 12,
            "name": "roar"
        }
    ],
    "status": "available"
}] but found [{
    "id": 356098,
    "category": {
        "id": 2,
        "name": "kitten"
    },
    "name": "roar",
    "photoUrls": [
        "www.amazon.com"
    ],
    "tags": [
        {
            "id": 12,
            "name": "roar"
        }
    ],
    "status": "available"
}]
at api_tests.PetStoreTest.addNewPetWithJsonFile(PetStoreTest.java:164)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- addNewPetWithJsonFile -->
  <testcase classname="api_tests.PetStoreTest" name="deletePet" time="0.437">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api_tests.PetStoreTest.deletePet(PetStoreTest.java:259)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- deletePet -->
  <testcase classname="api_tests.PetStoreTest" name="deletePetWithOath2" time="0.395"/>
  <testcase classname="api_tests.PetStoreTest" name="findById" time="0.14">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api_tests.PetStoreTest.findById(PetStoreTest.java:68)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- findById -->
  <testcase classname="api_tests.PetStoreTest" name="findByInvalidId" time="0.423"/>
  <testcase classname="api_tests.PetStoreTest" name="findByInvalidUrl" time="0.187"/>
  <testcase classname="api_tests.PetStoreTest" name="findByStaus" time="0.752"/>
  <testcase classname="api_tests.PetStoreTest" name="updatePet" time="0.388"/>
</testsuite> <!-- Smoke -->
